---
name: Pre-commit checks

on: [pull_request]

permissions: read-all

jobs:
  precommit:
    runs-on: ubuntu-latest
    name: Run pre-commit checks
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y python3 python3-pip curl unzip shfmt

          pip3 install pre-commit
          pip3 install checkov==2.3.148

      - name: pre-commit run
        run: |
          # this path is needed for pre-commit
          export PATH="~/.local/bin:$PATH"

          pre-commit run \
            --show-diff-on-failure \
            --from-ref origin/${GITHUB_BASE_REF} \
            --to-ref HEAD
