---
default_language_version:
  # force all unspecified python hooks to run python3
  python: python3
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.3
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
        exclude: '^[^/]+$'

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
        exclude_types: [svg]
      - id: pretty-format-json
        args:
          - --autofix
          - --no-sort-keys
      - id: check-added-large-files
        args: ["--maxkb=4096"]
      - id: detect-private-key
      - id: check-case-conflict
      - id: check-executables-have-shebangs

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: debug-statements
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: files/(issue|motd)
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  # Shell script hooks
  - repo: https://github.com/cisagov/pre-commit-shfmt
    rev: v0.0.2
    hooks:
      - id: shfmt
        args:
          # Indent by two spaces
          - -i
          - "2"
          # Binary operators may start a line
          - -bn
          # Switch cases are indented
          - -ci
          # Redirect operators are followed by a space
          - -sr
  # Docker hooks
  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v3.0.1
    hooks:
      - id: docker-compose-check

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
        exclude_types: [svg]
      - id: check-added-large-files
        args: ["--maxkb=4096"]
      - id: detect-private-key
      - id: check-case-conflict
      - id: check-executables-have-shebangs

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.22.0
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
