---
- hosts: all
  become: yes
  tasks:
    - name: Setup "default-jre" and "default-jdk"
      ansible.builtin.apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      with_items:
        - default-jdk
        - default-jre
      become: yes
