---
- hosts: jenkins_server
  become: yes
  tasks:
    - name: Setup "nginx" package
      ansible.builtin.apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      with_items:
        - nginx-full
      become: yes

    - name: upload NGINX configuration to "/etc/nginx/sites-available/default"
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/sites-available/default
        owner: bin
        group: www-data
        mode: '0644'
      become: yes

    - name: Make sure a service unit is running
      ansible.builtin.systemd_service:
        state: restarted
        name: nginx
        enabled: true
      become: yes

    - name: Create a symbolic link "/etc/nginx/sites-available/default" -> "/etc/nginx/sites-enabled/default"
      ansible.builtin.file:
        src: "/etc/nginx/sites-available/default"
        dest: "/etc/nginx/sites-enabled/default"
        owner: www-data
        group: www-data
        state: link
      become: yes
